version: "3.7"

# docker run -dp 3000:3000 `
  # -w /app -v "$(pwd):/app" `
  # --network todo-app `
  # -e MYSQL_HOST=mysql `
  # -e MYSQL_USER=root `
  # -e MYSQL_PASSWORD=secret `
  # -e MYSQL_DB=todos `
  # node:12-alpine `
  # sh -c "yarn install && yarn run dev"

services:
  clab:
    image: elixir:1.12.3
#    command: sh -c "yarn install && yarn run dev"

    #WINDOWS
    command: sh -c " apt-get update && apt-get upgrade && apt-get install -y npm && mix local.hex --force && mix deps.get && npm run build && npm run start"
    #UNIX / MAC
#    command: sh -c "mix deps.get && mix deps.compile && iex -S mix"
    ports:
      - 4001:4001
    working_dir: /CoachLab
    volumes: 
      - ./:/CoachLab
    environment:
      ENV: prod
      MIXENV: prod
  # mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - todo-mysql-data:/var/lib/mysql
  #   environment: 
  #     MYSQL_ROOT_PASSWORD: secret
  #     MYSQL_DATABASE: todos
# volumes:
#   todo-mysql-data: