{application,clab,
             [{modules,['Elixir.Agenda','Elixir.AutoMailer','Elixir.Clab',
                        'Elixir.Clab.Application','Elixir.Clab.AuthPlug',
                        'Elixir.Clab.Mailer','Elixir.Clab.ProtectedRouter',
                        'Elixir.Clab.PublicRouter','Elixir.Clab.Router',
                        'Elixir.DataSaver','Elixir.ImageMover','Elixir.Jwt',
                        'Elixir.Reservation','Elixir.Stripe',
                        'Elixir.StripeApi','Elixir.Twilio','Elixir.TwilioApi',
                        'Elixir.User','Elixir.Utils']},
              {compile_env,[{clab,[env],{ok,dev}},
                            {clab,[max_upload_file_size],error},
                            {clab,[port],{ok,8001}},
                            {clab,[stripe],
                                  {ok,#{url =>
                                            <<"https://api.stripe.com/v1/">>,
                                        test_sid => <<"test_sid_gl">>,
                                        test_secret =>
                                            <<"stripe_test_secret">>,
                                        test_mode => true,
                                        live_secret =>
                                            <<"live_secret_stripe">>}}},
                            {clab,[twilio],
                                  {ok,#{name => <<"clab-test">>,
                                        url =>
                                            <<"https://video.twilio.com/v1/">>,
                                        secret => <<"rerebelotte">>,
                                        account_sid => <<"my_sid_not_yours">>,
                                        account_secret =>
                                            <<"my_secret_not_yours">>,
                                        sid => <<"rebelotte">>}}},
                            {clab,[url],{ok,<<"http://localhost:80">>}}]},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,crypto,eex,plug,
                             cowboy,plug_cowboy,poison,mailibex,gen_smtp,
                             joken,httpoison,hackney,timex,mime]},
              {description,"clab"},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Clab.Application',[]}}]}.
